stages:
  # - test
  # - wp_build
  - theme_build_deploy

image: lynxsolutions/docker-composer-php7.1

variables:
  MYSQL_DATABASE: wordpress
  MYSQL_ROOT_PASSWORD: wordpress

cache:
  paths:
  - vendor/
  - web/

before_script:
  - ROOTPWD=`pwd`
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - sh scripts/before_script.sh

# test:
#   stage: test
#   cache:
#     key: bundles
#     paths:
#     - vendor/
#     - web/
#   script:
#   - cd $ROOTPWD
#   - sh scripts/test.sh
#   allow_failure: true
#
# wp_build:
#   stage: wp_build
#   cache:
#     key: bundles
#     paths:
#     - vendor/
#     - web/
#   script:
#   - cd $ROOTPWD
#   - sh scripts/wp_build.sh
#   allow_failure: true

theme_build_deploy:
  stage: theme_build_deploy
  cache:
    key: bundles
    paths:
    - vendor/
    - web/
  script:
    - cd $ROOTPWD
    - sh scripts/theme_build_deploy.sh

  artifacts:
    paths:
    - vendor/
    - web/
    expire_in: 1 week
  environment:
    name: production
    # url: http://dev-carlwpsecuritymu.pantheonsite.io/
  only:
  - master
