stages:
  - test
  - deploy

image: lynxsolutions/docker-composer-php7.1

variables:
  MYSQL_DATABASE: wordpress
  MYSQL_ROOT_PASSWORD: wordpress

cache:
  paths:
  - vendor/
  - web/

before_script:
  - sh scripts/before_script.sh

test:
  stage: test
  cache:
    key: bundles
    paths:
    - vendor/
    - web/
  script:
  - export THEMETOCHECK=$ROOTPWD/web/wp-content/themes/twentyseventeen-child
  - export PHPCS_DIR=$ROOTPWD/vendor/squizlabs/php_codesniffer/bin #phpcs v >3
  - export SNIFFS_DIR=$ROOTPWD/vendor/wp-coding-standards/wpcs
  - $PHPCS_DIR/phpcs --config-set installed_paths $SNIFFS_DIR
  - $PHPCS_DIR/phpcs -p $THEMETOCHECK --standard=WordPress --ignore=*gulpfile.js*,*/assets/*,*.css*
  allow_failure: true

deploy:
  stage: deploy
  cache:
    key: bundles
    paths:
    - vendor/
    - web/
  script:
  - echo "We need to put the gulp build here and only transfer assets, option for full or partial build!!"
  - cd $ROOTPWD
  - export ENV=dev
  - terminus auth:login --machine-token=$MACHINETOKEN --email=$EMAIL
  - terminus connection:set $PANTHEONSITENAME.dev sftp
  - rsync -Lvz --size-only --ipv4 -a --delete --progress -e 'ssh -p 2222' ./. --temp-dir=~/tmp/ $ENV.$SITE@appserver.$ENV.$SITE.drush.in:code/ --exclude=".git*"
  - rsync -Lvz --size-only --ipv4 -a --delete --progress -e 'ssh -p 2222' ./web/. --temp-dir=~/tmp/ $ENV.$SITE@appserver.$ENV.$SITE.drush.in:code/web/ --exclude=".git*"
  - rsync -Lvz --size-only --ipv4 -a --delete --progress -e 'ssh -p 2222' ./vendor/. --temp-dir=~/tmp/ $ENV.$SITE@appserver.$ENV.$SITE.drush.in:code/vendor/ --exclude=".git*"
  - rsync -rLvz --size-only --ipv4 --progress -e 'ssh -p 2222' ./web/. --temp-dir=~/tmp/ $ENV.$SITE@appserver.$ENV.$SITE.drush.in:code/web/ --exclude=".git*"
  - rsync -rLvz --size-only --ipv4 --progress -e 'ssh -p 2222' ./vendor/composer/. --temp-dir=~/tmp/ $ENV.$SITE@appserver.$ENV.$SITE.drush.in:code/vendor/composer/ --exclude=".git*"
  - rsync -rLvz --size-only --ipv4 --progress -e 'ssh -p 2222' ./vendor/johnpbloch/. --temp-dir=~/tmp/ $ENV.$SITE@appserver.$ENV.$SITE.drush.in:code/vendor/johnpbloch/ --exclude=".git*"
  - echo $CI_COMMIT_MESSAGE
  - terminus env:commit --message "GitLab:$CI_COMMIT_MESSAGE" --force -- $PANTHEONSITENAME.$ENV
  - terminus env:deploy --note "GitLab:$CI_COMMIT_MESSAGE" -- $PANTHEONSITENAME.test

  artifacts:
    paths:
    - vendor/
    - web/
    expire_in: 1 week
  environment:
    name: production
    # url: http://dev-carlwpsecuritymu.pantheonsite.io/
  only:
  - master
