stages:
  - test
  - wp_build
  - theme_build_deploy

image: lynxsolutions/docker-composer-php7.1

variables:
  MYSQL_DATABASE: wordpress
  MYSQL_ROOT_PASSWORD: wordpress

cache:
  paths:
  - vendor/
  - web/

before_script:
  - sh scripts/before_script.sh

test:
  stage: test
  cache:
    key: bundles
    paths:
    - vendor/
    - web/
  script:
  - export THEMETOCHECK=$ROOTPWD/web/wp-content/themes/twentyseventeen-child
  - export PHPCS_DIR=$ROOTPWD/vendor/squizlabs/php_codesniffer/bin #phpcs v >3
  - export SNIFFS_DIR=$ROOTPWD/vendor/wp-coding-standards/wpcs
  - $PHPCS_DIR/phpcs --config-set installed_paths $SNIFFS_DIR
  - $PHPCS_DIR/phpcs -p $THEMETOCHECK --standard=WordPress --ignore=*gulpfile.js*,*/assets/*,*.css*
  allow_failure: true

wp_build:
  stage: wp_build
  cache:
    key: bundles
    paths:
    - vendor/
    - web/
  script:
  - sh scripts/deploy.sh
  allow_failure: true

theme_build_deploy:
  stage: deploy
  cache:
    key: bundles
    paths:
    - vendor/
    - web/
  script:
    - sh scripts/deploy.sh

  artifacts:
    paths:
    - vendor/
    - web/
    expire_in: 1 week
  environment:
    name: production
    # url: http://dev-carlwpsecuritymu.pantheonsite.io/
  only:
  - master
